guest_list = ['larry bird', 'steve jobs', 'dad']
print(f"The three people I would invite to a dinner party is {guest_list}.")
print(f"I would invite {guest_list[0].title()}, because he is my favorite basketball player.")
print(f"I would invite {guest_list[1].title()}, because I would really like to know how his brain works.")
print(f"I would invite {guest_list[2].title()}, because I miss him a lot and have a shit ton of questions I want to ask him.")
print("I just found out that there is a bigger table, and I cant invite more people")
guest_list.insert(0, 'chuck russell')
guest_list.insert(2, 'joel kirch')
guest_list.append('ada lovelace')
print(guest_list)
print("I had to reprint the list because of all the added names. Now I can send out invitations to everyone.")
print(f"I would invite {guest_list[0].title()}, because I know he would love to talk to Bird.")
print(f"I would invite {guest_list[1].title()}, because he is my favorite basketball player.")
print(f"I would invite {guest_list[2].title()}, because I respect him so much and he would really enjoy talking to some of these guest.")
print(f"I would invite {guest_list[3].title()}, because I would really like to know how his brain works.")
print(f"I would invite {guest_list[4].title()}, because I miss him a lot and have a shit ton of questions I want to ask him.")
print(f"I would invite {guest_list[5].title()}, because she is such an iconic part or technology.")
print("I just found out that the bigger table won't be ready in time for dinner. Unfortunately, I can now only invite 2 people to dinner.")
removed_guest = guest_list.pop()
print(f"I'm really sorry {removed_guest.title()}, but I have to reschedule our dinner, because there isn't enough room in the restaurant.")
removed_guest = guest_list.pop()
print(f"Okay, {removed_guest.title()}, I will talk to you in my thoughts and dreams. The table is too small.")
removed_guest = guest_list.pop(0)
print(f"{removed_guest.title()}, I see you all the time, so we will get together some other time for dinner.")
removed_guest = guest_list.pop(1)
print(f"Sorry {removed_guest.title()}, but the table is too small. I hope to see you soon.")
print(f"{guest_list[0].title()}, we are still having dinner even though the table is smaller. See you there!")
print(f"{guest_list[1].title()}, we are still having dinner even though the table is smaller. See you there!")
del guest_list[0]
del guest_list[0]
print(guest_list)