guest_list = ['larry bird', 'steve jobs', 'dad']
print(f"The three people I would invite to a dinner party is {guest_list}.")
print(f"I would invite {guest_list[0].title()}, because he is my favorite basketball player.")
print(f"I would invite {guest_list[1].title()}, because I would really like to know how his brain works.")
print(f"I would invite {guest_list[2].title()}, because I miss him a lot and have a shit ton of questions I want to ask him.")
print("I just found out that there is a bigger table, and I cant invite more people")
guest_list.insert(0, 'chuck russell')
guest_list.insert(2, 'joel kirch')
guest_list.append('ada lovelace')
print(guest_list)
print("I had to reprint the list because of all the added names. Now I can send out invitations to everyone.")
print(f"I would invite {guest_list[0].title()}, because I know he would love to talk to Bird.")
print(f"I would invite {guest_list[1].title()}, because he is my favorite basketball player.")
print(f"I would invite {guest_list[2].title()}, because I respect him so much and he would really enjoy talking to some of these guest.")
print(f"I would invite {guest_list[3].title()}, because I would really like to know how his brain works.")
print(f"I would invite {guest_list[4].title()}, because I miss him a lot and have a shit ton of questions I want to ask him.")
print(f" I would invite {guest_list[5].title()}, because she is such an iconic part or technology.")